services:
  - type: web
    name: django-crm
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: django-crm-db
          property: connectionString
    buildCommand: docker build -t django-crm .
    startCommand: >
      sh -c "python manage.py migrate &&
             gunicorn crm.wsgi:application --bind 0.0.0.0:$PORT --timeout 120"

databases:
  - name: django-crm-db
    databaseName: django_crm
    plan: free